### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by p4st0r** [FriendsOfFlarum/nightmode#15]
**I met a problem about this**
![b m7xs i39 8 h 0 i](https://user-images.githubusercontent.com/10896384/53492627-45cc3780-3ad4-11e9-830f-59eb8bda276a.png)

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
```

**Comment by Ralkage** [comment]
@p4st0r still having this issue? Please respond within 7 days or this will be presumed as no longer an issue :)

**Comment by gwillem** [comment]
Can confirm this issue on all FreeFlarum forums. Disabling reflar/nightmode recovers the error.

![](https://buq.eu/screenshots/Ltvqpx2B3eKGOGoMo0M8Alla.png)

Possibly related:
![](https://buq.eu/screenshots/Wdg9Nleoza2VcybuigHVXYRu.png)

**Comment by datitisev** [comment]
This can be fixed with an initializer priority. We also probably want to make sure flarum/tags is loaded & enabled before extending anything.

**Comment by Ralkage** [comment]
@gwillem @p4st0r we're going to attempt to fix this issue before we release this into the FoF namespace.

@datitisev suggests wrapping that TagsPage extender with `if (TagsPage)` but we'll see what that does 👍
