### ISSUE TITLE
Remove Background from .DiscussionListItem-count

### ISSUE THREAD

**Issue by oaklinq** [FriendsOfFlarum/nightmode#16]
Pretty small thing, but I would like to have the background of .DiscussionListItem-count to be removed. In standard flarum this element doesn't has a background and I don't think it really needs one in dark mode. On the other hand it is visible when the hover color of the .DiscussionListItem is changed:
![screen](https://i.imgur.com/5dvdbgO.png)

**Comment by misprinted** [comment]
I second that.

Other items with the class `.Dropdown-menu` also have this issue.
Meanwhile I'm overriding them with the `.dark` class 🙌

**Comment by Ralkage** [comment]
@oaklinq or @misprinted feel free to submit a PR so that we can get a fix deployed ASAP 👍

**Comment by Ralkage** [comment]
This has been fixed in my latest commits.
