### ISSUE TITLE
Composer textarea placeholders are dark

### ISSUE THREAD

**Issue by davwheat** [FriendsOfFlarum/nightmode#24]

**Comment by Ralkage** [comment]
@davwheat why did you open and immediately close this issue?

**Comment by davwheat** [comment]
Because this was meant to go on my fork of this repo. I've rewritten all the styles for my forum's needs. I realised so closed the issue.

Whether it actually also happens with this repo is another case.

**Comment by Ralkage** [comment]
@davwheat curious to see your style changes, would you be able to share? If you prefer for it to remain private, you can share with me as well and I can test locally :)

**Comment by davwheat** [comment]
Sure! It's open source: https://github.com/imorland/nightmode
