### ISSUE TITLE
Nightmode CSS overrides Custom CSS

### ISSUE THREAD

**Issue by phenomlab** [FriendsOfFlarum/nightmode#29]
In vendor > fof > nightmode > resources > less > forum > extension.less line 115 - each time I update this extension, I have to override as below

```
    .App:before {
        background: rgba(0,0,0,0.1);
    }
```

This is required to match my existing theme - otherwise, the header is loaded with a style that seems to override that which is in custom CSS. Can this be looked at also ?

**Comment by BigMinnie** [comment]
The put !important into the css when they would not need to, don't know why nobody updates that simple thing...

**Comment by datitisev** [comment]
The way this extension implements the dark mode isn't great. It'd be better to have two CSS files - one for dark mode, and one for light mode - but last time I checked that wasn't very easy. We do want to improve this extension. 

> They put !important into the css when they would not need to, don't know why nobody updates/removes that simple thing...

Where exactly are you talking about? I assume the !important used is to override the default forum scheme. I understand it's not desirable.

**Comment by BigMinnie** [comment]
@datitisev check my pull request

**Comment by datitisev** [comment]
Fixed
