### ISSUE TITLE
For anonymous users ?

### ISSUE THREAD

**Issue by KabDeveloper** [FriendsOfFlarum/nightmode#35]
Hi

Thank you for this work !

Is it possible to purpose this function to anonymous users ?

Thank you

**Comment by imorland** [comment]
Yes! This feature is present in this PR:https://github.com/FriendsOfFlarum/nightmode/pull/33

Once merged, this will provide what you ask for

**Comment by bcashier** [comment]
Can you provide the steps for making it working please ?

I don't have any idea on how to merge the PR.

@imorland big thanks !

**Comment by imorland** [comment]
It's still under review by the team at the moment, and the PR author has been requested to make some minor changes. Once that is done, we will merge and publish a new release

**Comment by bcashier** [comment]
@imorland There is no way I can do it by myself right now ?

If I install this: https://github.com/imorland/nightmode

I will get the expected result ?

Thank you again and sorry for your time

**Comment by imorland** [comment]
The repo you linked to there is a highly customized one for a specific community. It will likely cause issues if you were to install that one.

I _really_ would just wait a short while longer for this update to be released. :)

**Comment by bcashier** [comment]
I will, thank you !

**Comment by datitisev** [comment]
This isn't present in 0.5.0. I'll reopen in case I do add this at some point.

**Comment by bcashier** [comment]
Feature added or not yet ?

Thank you !

**Comment by datitisev** [comment]
Not added yet.

**Comment by bcashier** [comment]
Oh ok I see :( 

Looking forward for it !

**Comment by PeopleInside** [comment]
I'm looking for the same.

**Comment by Leanerz** [comment]
For when please?

**Comment by PeopleInside** [comment]
No update on this? :(
