### ISSUE TITLE
Replace gear icon with FontAwesome `fo-sun` icon

### ISSUE THREAD

**Issue by hvanmegen** [FriendsOfFlarum/nightmode#40]
I couldn't directly find where the icon was defined, but can we replace that gear icon with the fo-sun FontAwesome sun icon or is it missing from the Flarum FontAwesome icon set?

**Comment by hvanmegen** [comment]
Nevermind.. that Sun icon looks like a gear because of the inner circle.

**Comment by datitisev** [comment]
We are currently using `far fa-sun` (https://fontawesome.com/icons/sun?style=regular)

https://github.com/FriendsOfFlarum/nightmode/blob/b871bc84c69ce4d4326b7188c757c280ceecb2af/js/src/forum/addSettingsItems.js#L111.

We might want to change it to `fas` to make it easier to identify & keep the icon scheme of the other session dropdown items.

**Comment by hvanmegen** [comment]
I was thinking more in lines of https://fontawesome.com/v4.7.0/icon/sun-o .... the current icon looks like a gear.

**Comment by datitisev** [comment]
We're using FA 5 so that is not possible. I think the solid icon would still be an improvement and look less like a gear, as you say.
