### ISSUE TITLE
Beta 14 support?

### ISSUE THREAD

**Issue by AlexanderOMara** [FriendsOfFlarum/nightmode#41]
### Instructions (MUST READ FIRST)

Before we can address your issues and concerns with the behavior of our work, we require every bit of detail from you to the fullest extent of this form. If this form is not properly filled out to it's entirity, we, ReFlar, reserve the right to close your issue due to lack of information thereof as well as not following instructions.

* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Please Mentally Go Over the Following Items Before Filling Out this Form:

* Can you reproduce this problem in debug mode?
* Are you running the latest version of this extension?
* Is your Flarum up-to-date?

### Description

Flarum 14 doesn't appear to be supported, with Flarum's breaking changes like Mithril 2 and Laravel 6.

### Steps to Reproduce

1. Install Flarum beta 14.
2. Activate extension.
3. Encounter breaking changes.

Looks like a pending pull request might cover these issues: https://github.com/FriendsOfFlarum/nightmode/pull/38

**Comment by clarkwinkelmann** [comment]
As announced, the Friends Of Flarum group is working hard to get the extensions updated in the shortest amount of time possible https://discuss.flarum.org/d/16242-friends-of-flarum-the-collaboration-for-maintained-extensions/33

We will use the extension discussion on Flarum Discuss to announce updates. Until that happens, extensions should be considered not compatible. To keep our workload to a minimum, I'm closing this issue and we'll post updates on the forum.

If you would like to help us, see the link above for some suggestions. Thanks!
