### ISSUE TITLE
[feature] Set default mode

### ISSUE THREAD

**Issue by Psychokiller1888** [FriendsOfFlarum/nightmode#42]
He! Thanks for that extension, it's awesome!

Would love to set my board as dark mode by default. So I thought that this extension is tight to the "dark mode switch" on the admin. But if I set my board as dark mode, well, you can't have light mode anymore :)

**Comment by matteocontrini** [comment]
You can already do that in the extension settings

**Comment by Psychokiller1888** [comment]
Ok, gimme a rope, or better, a shovel so I can dig myself a hole to hide in.... sry....

**Comment by matteocontrini** [comment]
😄 don't worry, it's indeed confusing
