### ISSUE TITLE
Text/Icon colors on colored backgrounds change in Dark Mode

### ISSUE THREAD

**Issue by tipa** [FriendsOfFlarum/nightmode#46]
### Description
Just installed this plugin and love it - nice work.
I am using a "Colored header" and noticed that switching the theme also changes the text color on colored surfaces (like the colored header, the tags & the colored buttons). Wouldn't it make sense to keep the that color to white to ensure readability?
I've already skimmed through the last years comments on this thread but didn't see this question brought up yet.

### Steps to Reproduce
1. Enable Night mode in admin settings
2. Enable "Colored header" and set color to "#5572F7"
3. Go back to main page
![image](https://user-images.githubusercontent.com/2863198/107187332-217a7480-69e6-11eb-8471-8a57b9a7d2b3.png)

**Expected Behavior:**
Texts on colored backgrounds continue to use a bright color.
Other web apps (Twitter, GitHub) also mostly use bright colors on their colored buttons

**Actual Behavior:** 
Texts on colored background switched to dark text/icon color

## Technical Details

- Version of Flarum (0.1.0-beta.15):
- Version of extension (0.7.1):
- The webserver you are running (Apache):
- PHP version (7.4.15):
- Hosted environment (Shared):
- Hosting provider (https://uberspace.de/):

## Flarum Info

```
Flarum core 0.1.0-beta.15
PHP version: 7.4.15
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, restrictdocroot, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mysqlnd, PDO, pgsql, Phar, posix, shmop, SimpleXML, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, xmlreader, xmlrpc, apcu, decimal, gnupg, igbinary, imagick, msgpack, psr, yaml, zip, mongodb, phalcon, redis, Zend OPcache
+----------------------+------------------+--------+
| Flarum Extensions    |                  |        |
+----------------------+------------------+--------+
| ID                   | Version          | Commit |
+----------------------+------------------+--------+
| flarum-approval      | v0.1.0-beta.15   |        |
| flarum-bbcode        | v0.1.0-beta.15   |        |
| flarum-emoji         | v0.1.0-beta.15   |        |
| flarum-lang-english  | v0.1.0-beta.15   |        |
| flarum-flags         | v0.1.0-beta.15   |        |
| flarum-lock          | v0.1.0-beta.15   |        |
| flarum-markdown      | v0.1.0-beta.15   |        |
| flarum-mentions      | v0.1.0-beta.15   |        |
| flarum-statistics    | v0.1.0-beta.15   |        |
| flarum-sticky        | v0.1.0-beta.15.1 |        |
| flarum-subscriptions | v0.1.0-beta.15   |        |
| flarum-suspend       | v0.1.0-beta.15   |        |
| flarum-tags          | v0.1.0-beta.15   |        |
| fof-polls            | 0.3.2            |        |
| fof-user-directory   | 0.5.0            |        |
| fof-oauth            | 0.2.1            |        |
| flarum-likes         | v0.1.0-beta.15   |        |
| flarum-nicknames     | v0.1.0-beta.15   |        |
| fof-nightmode        | 0.7.1            |        |
+----------------------+------------------+--------+
Base URL: https://workinghours.timopartl.com
Debug mode: off
```

**Comment by datitisev** [comment]
This extension doesn't have any CSS styles. The dark mode it uses is Flarum's own. Check if you're able to reproduce just by using Flarum's dark mode (disable this ext first), then if so make an issue @ flarum/core 🙂

**Comment by tipa** [comment]
Thanks for the clarification. I am able to reproduce the issue with the "forced" Dark Mode from Flarum. Will file an issue there.
