### ISSUE TITLE
Poor interaction with Flarum Embed due to link rewrite.

### ISSUE THREAD

**Issue by lhunath** [FriendsOfFlarum/nightmode#47]
## Bug Report

**Current Behavior**
While Nightmode is enabled, the plugin replaces:
```
-<link rel="stylesheet" media="" class="nightmode-dark" href="https://chat.spectre.app/assets/forum-dark-206d3f11.css">
+<link rel="stylesheet" media="" class="nightmode" href="https://chat.spectre.app/assets/embed-dark-607a4491.css">
```

**Steps to Reproduce**
1. Enable [Flarum/Embed](https://github.com/flarum/embed)
2. Enable FoF/NightMode
3. Open an embed URL for a post, eg. https://chat.spectre.app/embed/40-an-algorithm-for-freedom
4. Notice forum CSS is removed and basic style is no longer applied.
5. Turn off JavaScript
6. Forum CSS is no longer removed.

**Environment**
- Flarum version: 0.1.0-beta.15
- Extension version: 0.7.1
- Website URL: https://chat.spectre.app
- Hosting environment: Free Flarum
- Browser: Firefox 87

**Comment by clarkwinkelmann** [comment]
Yep, it seems like Nightmode doesn't work with "hybrid frontends", which is what Flarum Embed and my own Wordpress Integration extensions use.

In those "hybrid frontends", there are two css and two js files loaded, one is from the `forum` frontend and is the same file used on the main Flarum page, and a second file is loaded based on the name of the custom frontened.

The javascript isn't impacted, but Nightmode logic causes the two CSS files to be replaced by a single link to the second one.

I had a look at this issue a few months ago but wasn't seeing any obvious solution that didn't require re-writing a large portion of Nightmode :sweat_smile: 

I'm tracking this internally at https://github.com/clarkwinkelmann/flarum-ext-wordpress/issues/3

**Comment by ramesh-dada** [comment]
Yes this issue still exists, I am unable to see page clearly the page is without css due to 

> ## Bug Report
> While Nightmode is enabled, the plugin replaces:
> ```
> -<link rel="stylesheet" media="" class="nightmode-dark" href="https://chat.spectre.app/assets/forum-dark-206d3f11.css">
> +<link rel="stylesheet" media="" class="nightmode" href="https://chat.spectre.app/assets/embed-dark-607a4491.css">
> ```
