### ISSUE TITLE
Colored headers not darkened

### ISSUE THREAD

**Issue by Eumobong** [FriendsOfFlarum/nightmode#48]
## Feature Request

**Is your feature request related to a problem? Please describe.**

If colored header is enabled in appearance tab of Admin, the colored header is retain even in dark mode for all users.

**Describe the solution you'd like**

If the admistrator enables colored headers in Admin, the colored headers should be darkened when someone visits the forum frontend and enables dark mode. 

**Describe alternatives you've considered**

Nil

**Comment by clarkwinkelmann** [comment]
I think that behavior comes from Flarum itself. All this extension does is switching Flarum's dark mode on and off.

We could add an option to define a value for "Colored header" setting depending on selected dark mode, but I think it's a bit too much complexity to add to this extension.

The other option if for you to define your own custom dark mode CSS that overrides the header color. There are some examples on the forum on how to add custom CSS that only applies to dark mode.
