### ISSUE TITLE
Some small issues v 1.1.6

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/nightmode#55]
Can I report a small issue maybe present also before?

Checkboxes like when you flag a post and need select an option or the check box to stay logged still have dark background if the light theme is active. Can be this fixed? The issue is resolved if the extension night mode is turned off.

Another small issue with the new extension is that night mode miss the night mode text.

Screenshots:

![1](https://i.postimg.cc/xjGxcV4N/1.png)

![2](https://i.postimg.cc/pXqsJYx2/2.png)

![3](https://i.postimg.cc/K8jJqkvt/3.png)

Thanks

**Comment by datitisev** [comment]
Both issues should be fixed in `v1.1.7`
