### ISSUE TITLE
Bad color visual in dark mode: code

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/nightmode#65]
## Bug Report

**Current Behavior**

In Dark mode some strings of the code are not visible.

See here: 
https://discuss.flarum.org/d/21492-friendsofflarum-night-mode/365

**Comment by n-peugnet** [comment]
You might be interested in the extension I made that fixes this issue (among other things): [CLUB1 Server Side Highlight](https://discuss.flarum.org/d/32811-server-side-highlight).

It provides the following advantages:

1. The highlighting is done on the server so it is not up to the clients to do it.
2. The server uses the cache to save highlighted blocks to only do the processing once.
3. It works without any JS so even on the worst web browser the highlight will be there and there is no delay before the highlighting is applied.
4. The theme adapts itself to the "dark mode" setting of Flarum.
5. It works even with BBCode extension disabled.
6. Admins can choose the highlight theme for both "Light" and "Dark" Flarum variants.
7. Admins can download highlight themes with `highlight:download` [Flarum console](https://docs.flarum.org/console/) command.
8. It is compatible with [`fof/nightmode >= 1.5.2`](https://github.com/FriendsOfFlarum/nightmode) by switching the highlight theme accordingly.

**Comment by PeopleInside** [comment]
Thank you, but why this extension fix only new post?
Once is active will edit how message are posted so this is the reason I read the changes will be applied only to new comments? :)

**Comment by n-peugnet** [comment]
> Thank you, but why this extension fix only new post?
> Once is active will edit how message are posted so this is the reason I read the changes will be applied only to new comments? :)

Yes, this extension applies the highlight in the backend. It modifies the parser, who is responsible for analyzing the posts when they are sent. This is to minimize the amount of processing when reading the posts.

[As recommended](https://github.com/club-1/flarum-ext-server-side-highlight#recommendation), you can use `php flarum chore:reparse` from the [`club-1/flarum-ext-chore-commands` extension](https://github.com/club-1/flarum-ext-chore-commands) to parse again all previous posts. Note that other extensions might also affects the parser, so it could change more than just je code highlighting on old posts.

**Comment by dsevillamartin** [comment]
Closing since this extension isn't responsible for what dark mode looks like, only activating it.
