### ISSUE TITLE
Scrollbar displays incorrect in Auto mode

### ISSUE THREAD

**Issue by DellZHackintosh** [FriendsOfFlarum/nightmode#71]
https://github.com/FriendsOfFlarum/nightmode/issues/58#issue-1167865039 pointed out that wrong `color-scheme` can cause the incorrect appearance of scrollbar, and then the problem solved.
But I think it's not a perfect solution......When the option is `Automatic (based on browser or device options)` and the device is in dark mode, the same problem appears.
The better solution I think is set `color-scheme` to `light dark` when the `Automatic (based on browser or device options)` option is active.

**Comment by dsevillamartin** [comment]
I think the issue is the `color-scheme` `<meta>` tag not being updated, rather than the `:root` color-scheme.

**Comment by DellZHackintosh** [comment]
But it can't be solved too.
Add these CSS can solve the problem temporarily:
```
& when (@config-dark-mode = false) {
	color-scheme: light;
}
& when (@config-dark-mode = true) {
	color-scheme: dark;
}
```

**Comment by dsevillamartin** [comment]
@DellZHackintosh Not sure what you mean? Did v1.5.3 not fix this issue?

**Comment by DellZHackintosh** [comment]
Ouch, I didn't notice that😅
Then no problem anymore. Thanks.
